### ISSUE TITLE
Main screen hard to read when using Dark Theme

### ISSUE THREAD

**Issue by Connor9220** [knipknap/better-tool-library#16]
Using ProDarkThemePack -- OpenDark looks a bit better, but the gray color still doesn't show up very well.

![Screenshot from 2024-01-16 01-48-35](https://github.com/knipknap/better-tool-library/assets/833255/99f93b9a-4ec1-4662-8221-4f2c50b801b2)

Sub pages look a bit better

![Screenshot from 2024-01-16 01-53-37](https://github.com/knipknap/better-tool-library/assets/833255/be36a5c4-61cd-45e7-a32f-ef5dcaa48969)

All end mill images could use more contrast or something.

**Comment by knipknap** [comment]
I added some logic to improve contrast in dark themes, but it seems that the ProDark theme is simply broken and overwrites this. In other words, it styles things that just shouldn't be styled - even though I explicitly assigned the text color to each of the labels, the color is still not used when that theme is active.

It looks like this cannot be fixed in BTL - or if anyone knows how please provide a patch.

**Comment by Connor9220** [comment]
Here's what the main screen looks like in OpenDark

![Screenshot from 2024-01-16 17-04-49](https://github.com/knipknap/better-tool-library/assets/833255/75ec5b84-344e-463b-80e0-6ee5cb6593f1)

**Comment by knipknap** [comment]
I now understand theming of FreeCAD better than when the issue was opened: This is actually not something BTL can or should control.

In other words, such bugs need to be reported to the theme author instead - I cannot fix it.
